# Generated by Django 5.1.2 on 2024-10-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='city',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
